"""Grocery Tracker - Intelligent grocery list and inventory management."""

from .analytics import Analytics
from .config import ConfigManager
from .data_store import BackendType, DataStore, create_data_store
from .inventory_manager import InventoryManager
from .list_manager import DuplicateItemError, ItemNotFoundError, ListManager
from .models import (
    BudgetTracking,
    Category,
    CategoryBudget,
    CategorySpending,
    FrequencyData,
    GroceryItem,
    GroceryList,
    InventoryItem,
    InventoryLocation,
    ItemRecommendation,
    ItemStatus,
    LineItem,
    OutOfStockRecord,
    PriceComparison,
    PriceHistory,
    PricePoint,
    Priority,
    PurchaseRecord,
    Receipt,
    ReconciliationResult,
    RouteItemAssignment,
    RouteStoreStop,
    SavingsContributor,
    SavingsRecord,
    SavingsSummary,
    ShoppingRoute,
    SpendingSummary,
    StorePreferenceScore,
    SubstitutionRecommendation,
    Suggestion,
    UserPreferences,
    WasteReason,
    WasteRecord,
)
from .output_formatter import OutputFormatter
from .receipt_processor import ReceiptInput, ReceiptProcessor
from .sqlite_store import SQLiteStore

__version__ = "1.0.0"

__all__ = [
    "Analytics",
    "BackendType",
    "BudgetTracking",
    "Category",
    "CategoryBudget",
    "CategorySpending",
    "ConfigManager",
    "create_data_store",
    "DataStore",
    "DuplicateItemError",
    "FrequencyData",
    "GroceryItem",
    "GroceryList",
    "InventoryItem",
    "InventoryLocation",
    "ItemRecommendation",
    "InventoryManager",
    "ItemNotFoundError",
    "ItemStatus",
    "LineItem",
    "ListManager",
    "OutOfStockRecord",
    "OutputFormatter",
    "PriceComparison",
    "PriceHistory",
    "PricePoint",
    "Priority",
    "PurchaseRecord",
    "Receipt",
    "ReceiptInput",
    "ReceiptProcessor",
    "ReconciliationResult",
    "RouteItemAssignment",
    "RouteStoreStop",
    "SavingsContributor",
    "SavingsRecord",
    "SavingsSummary",
    "ShoppingRoute",
    "SpendingSummary",
    "SQLiteStore",
    "StorePreferenceScore",
    "SubstitutionRecommendation",
    "Suggestion",
    "UserPreferences",
    "WasteReason",
    "WasteRecord",
]
