"""Grocery Tracker - Intelligent grocery list and inventory management."""

from .analytics import Analytics
from .config import ConfigManager
from .data_store import BackendType, DataStore, create_data_store
from .inventory_manager import InventoryManager
from .list_manager import DuplicateItemError, ItemNotFoundError, ListManager
from .models import (
    BudgetTracking,
    BulkBuyingRecommendation,
    Category,
    CategoryBudget,
    CategorySpending,
    Deal,
    DealType,
    FrequencyData,
    GroceryItem,
    GroceryList,
    InventoryItem,
    InventoryLocation,
    ItemStatus,
    LineItem,
    OutOfStockRecord,
    PriceComparison,
    PriceHistory,
    PricePoint,
    Priority,
    PurchaseRecord,
    Receipt,
    ReconciliationResult,
    SavingsRecord,
    SavingsSummary,
    SavingsType,
    SeasonalMonth,
    SeasonalPattern,
    SpendingSummary,
    Suggestion,
    UserPreferences,
    WasteReason,
    WasteRecord,
)
from .output_formatter import OutputFormatter
from .receipt_processor import ReceiptInput, ReceiptProcessor
from .sqlite_store import SQLiteStore

__version__ = "1.0.0"

__all__ = [
    "Analytics",
    "BackendType",
    "BudgetTracking",
    "BulkBuyingRecommendation",
    "Category",
    "CategoryBudget",
    "CategorySpending",
    "ConfigManager",
    "create_data_store",
    "DataStore",
    "Deal",
    "DealType",
    "DuplicateItemError",
    "FrequencyData",
    "GroceryItem",
    "GroceryList",
    "InventoryItem",
    "InventoryLocation",
    "InventoryManager",
    "ItemNotFoundError",
    "ItemStatus",
    "LineItem",
    "ListManager",
    "OutOfStockRecord",
    "OutputFormatter",
    "PriceComparison",
    "PriceHistory",
    "PricePoint",
    "Priority",
    "PurchaseRecord",
    "Receipt",
    "ReceiptInput",
    "ReceiptProcessor",
    "ReconciliationResult",
    "SavingsRecord",
    "SavingsSummary",
    "SavingsType",
    "SeasonalMonth",
    "SeasonalPattern",
    "SpendingSummary",
    "SQLiteStore",
    "Suggestion",
    "UserPreferences",
    "WasteReason",
    "WasteRecord",
]
